### PR TITLE
Issue125 dataset keyword definedterm

### PR DESCRIPTION
**Pull request by ashepherd**
Dataset Guide:
- Adds keywords section
- Demonstrates using Text
- Demonstrates using DefinedTerm

### CODE REVIEW

**Comment by ashepherd** [comment]
#125

**Comment by ashepherd** [comment]
Look to add examples from:

Nick Jarboe
https://www2.earthref.org/vocabularies/controlled 
Chantelle Verhey 
https://docs.google.com/spreadsheets/d/1mTvCH2995l73uqJa2Lt3KaIqsGxdy8CdraF7wPQc1D4/edit#gid=0

**Comment by smrgeoinfo** [comment]
I added a couple more definedTerm examples, in the text per https://github.com/ESIPFed/science-on-schema.org/pull/175#issuecomment-904591760

**Review by mbjones — APPROVED** [review]
The DefinedTerm changes look great.

**Pull request merged**
