### PR TITLE
Fix the 'publisher-provider' anchor link

### PR DESCRIPTION
**Pull request by nein09**
This link wasn't working because the actual anchor has an extra dash in it.

I wasn't sure which branch to make this PR against - I think it'd be fine against master too, but that's not strictly how things are done around here.

### CODE REVIEW

**Comment by mbjones** [comment]
There's a similar typo already merged into `develop`, so I think that is a good place, and then we can make a 3.0.1 soft release that merges those editorial changes into main.

In terms of your fix, would it be better to change the link target to use a single dash, to follow the pattern used in other TOC links?

**Comment by nein09** [comment]
The only hesitation about changing the target is that maybe other people have linked to it as-is already, but that doesn't seem super likely - i'll do it that way round.

**Comment by nein09** [comment]
Actually, since this is an auto-generated anchor, I think it might be better to keep this fix as-is.

**Comment by ashepherd** [comment]
@nein09 should we kill this PR? gonna make a 1.3.1 release later and wasn't sure if we should incorporate?

**Comment by mbjones** [comment]
After today's call, I reviewed this again, and revised the link text to eliminate the special character that was causing the double hyphen in the auto-generated link. So now the link is clear to `publisher-and-provider`. I will merge this to develop shortly for 1.3.1.

**Pull request merged**
