### PR TITLE
adds reserved Zenodo 1.3.1 DOI before

### PR DESCRIPTION
**Pull request by ashepherd**

### CODE REVIEW

**Review by njarboe — CHANGES_REQUESTED** [review]
Looks good but the Zenodo DOI is not active. Maybe that should be done first so the README does not have a broken link?

**Review by njarboe — CHANGES_REQUESTED** [review]
Do you need the merge to happen before you put the code on Zenodo or can you just use this branch for the Zenodo contribution pre-merge?

**Comment by ashepherd** [comment]
yeah, the workflow is a a little odd, first we reserve a DOI at zenodo, and then i update all the places we mention the DOI, then I package that up as a ZIP file and deposit at Zenodo for the reserved DOI. That gets the Zenodo DOI into the archived pkg.

**Comment by njarboe** [comment]
Ok. So should I merge now even though the Zenodo link will be broken?

**Comment by ashepherd** [comment]
Yeah, it's work once I publish the Zenodo versionafter putting the ZIP file in there

**Review by njarboe — APPROVED** [review]

**Pull request merged**
