### PR TITLE
add section on dates related to dataset per issue #208

### PR DESCRIPTION
**Pull request by smrgeoinfo**

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Thanks @smrgeoinfo - effective editing of the discussion into a practical outcome :-D

**Comment by nein09** [comment]
Agreed - this is immediately helpful for things I'm currently working on, as it happens.

**Comment by dr-shorthair** [comment]
Who gets to merge this?

**Comment by mbjones** [comment]
@dr-shorthair We generally discuss each issue on one of our two monthly calls and ensure we have agreement before merging. Our next call is tomorrow, so it should come up!

**Comment by mbjones** [comment]
Both @njarboe and @mbjones have now edited for clarity and conciseness, so I am merging this PR into `develop` based on our discussion today. Further wording revisions should occur in the `develop` branch as people review the final release.

**Pull request merged**
