### PR TITLE
Feature 13 specifying identifiers

### PR DESCRIPTION
**Pull request by ashepherd**
Pull request for Issue #13 

Updates to:

- [x] ADR - 13-schemaorg-identifier-as-PropertyValue.md
- [x] removes references to datacite ontology across guidelines
- [x] recommends using PropertyValue
- [x] recommends using schema:propertyID with URI from registry.identifiers.org
- [x] recommends using prefix and value in `schema:value` (e.g. doi:1234.56/7890)
- [x] updates Dataset guideline
    - [x] updates text, diagram and JSON-LD examples
- [x] updates Repository guideline
    - [x] updates text, diagram and JSON-LD example 
- [x] updates examples of dataset and repository

### CODE REVIEW

**Comment by rduerr** [comment]
OK, the text in the https://github.com/ESIPFed/science-on-schema.org/tree/feature_13_specifying_identifiers branch is not adequate.  Currently it says to use identifiers.org for identifiers, then it goes off and talks about using datacite.org.  That ends up creating yet another mishmash of identifier information content.  It would be better to say something like:

Leading Practice:

- Use datacite.org scheme if it exists
- Use identifies.org values as well

Consider putting examples of usage for each of the main types of identifiers used in a table by the leading practice.

**Comment by ashepherd** [comment]
Ooh, thanks for catching that Ruth. I’ll fix that. I intended to remove all refs to the Datacite ontology but I must’ve missed some

**Comment by rduerr** [comment]
Also I noticed that the text does not have an @ID for the dataset in it; but the example https://github.com/ESIPFed/science-on-schema.org/blob/master/examples/dataset/full.jsonld does. 

Is there any reason why @ID could not be used?  It would make things easier I think.  Currently it looks like straightforwardly converting to rdf from json-ld would result in a blank node at the identifier level (OK, so doing the conversion on line at https://rdf-translator.appspot.com/ did)

**Comment by ashepherd** [comment]
Yes, we can absolutely add an @id im for the identifier. I’ll make sure to do that before the pull request gets merged

**Comment by ashepherd** [comment]
comments by @rduerr fixed in 8a8b73cfc9117b97f84e0b223cc3965a6ca8a707

**Pull request merged**
